#攻击力加成不回累加,是在玩家基础攻击力上增加
setting:
  #当升级的时候是否全服广播
  broadCast: true
  #是否开启等级血量加成
  enableHealth: true
  #是否开启等级领地加成
  res:
    enable: true
    enabledWorlds:
    - world
  #是否开启等级攻击加层
  enableAttack: true
  #查看自己的等级信息时候显示的文字
  #可用的变量有:%player%,%level%,%point%,%maxPoint%,%resCount%,%resSize%,'%maxHealth%,%killMob%,%attack%'
  levelProfile:
  - '&e---------------------------------'
  - '&e玩家: &b&l%player%'
  - '&e爵位: &l%level%'
  - '&e---------------------------------'
  - '&e当前点数: &b%point% 点'
  - '&e升级所需: &b%maxPoint% 点'
  - '&e领地上限: &b%resCount% 个'
  - '&e领地最大: &b%resSize% 格'
  - '&e最大血量: &b%maxHealth% 点'
  - '&e击杀怪物: &b%killMob% 只'
  - '&e攻击加成: &b%attack% 点'
  - '&e---------------------------------'
  #等级列表
  levels:
    #不要删除这个等级
    default:
      #称号
      nick: '&ahobo'
      #最大血量
      health: 10
      resGroup: default
      #升级上限点数
      upgradePoints: 50
      #攻击力增加1点
      attack: 1
      #下一个等级名字
      nextLevel: 'nextLevel'
      #成为该等级以后自动执行的命令
      cmds:
      #成为该等级后拥有的权限
      permissions:
      levelPoints:
          #每个point的价格
          price: 10.0
          #单击一次购买多少点数
          amount: 1
    nextLevel:
      #称号
      nick: '&adenizen'
      #最大血量
      health: 10
      resGroup: default
      #升级上限点数
      upgradePoints: 200
      #攻击力增加1点
      attack: 1
      #下一个等级名字
      nextLevel:
      #成为该等级以后自动执行的命令
      cmds:
      #成为该等级后拥有的权限
      permissions:
      - 'essentials.balancetop,world,sc'
      levelSign:
        #每个point的加个
        price: 20.0
        #单击一次购买多少点数
        count: 10


